
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PSW}
      MYSQL_DATABASE: trancendance
      MYSQL_TCP_PORT: 5310
    ports:
      - "5310:5310"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: