openapi: 3.0.0

info:
  title: Car Renting API
  version: 0.1.0

servers:
  - url: http://localhost:3000/
    description: base url

tags:
  - name: Authentication
    description: User registration and login
  - name: Email Verification
    description: user Email Verification
paths:
  /api/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                first_name: John
                last_name: Doe
                email: JohnDoe@example.com
                password: password
                phone_number: "+111111111"
      responses:
        "201":
          description: Success
        "400":
          description: Bad Request

  /api/login:

    
    post:
      tags:
        - Authentication
      summary: Log in user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                email: JohnDoe@example.com
                password: password
      responses:
        "200":
          description: Login successfull
        "401":
          description: Wrong credentials
        "400":
          description: Bad Request
  /api/verify/{token}:
    post:
      parameters:
      - in: path
        name: token
        schema:
          type: string
        required: true
        description: token of the user to verify
      tags:
        - Email Verification
      summary: verify Email Adress
      responses:
        "200":
          description: Verification Successfull
        "401":
          description: Invalid token
        "500":
          description: Server failure
  /api/verify/refresh/{old_token}:
    post:
      parameters:
      - in: path
        name: old_token
        schema:
          type: string
        required: true
        description: token to be refreshed
      tags:
        - Email Verification
      summary: refresh verification token
      responses:
        "200":
          description: token refresh Successfull
        "401":
          description: Invalid token
        "500":
          description: Server failure